using Microsoft.EntityFrameworkCore;
using PulseDesk.Application.DTOs;
using PulseDesk.Application.Repositories.Abstract;
using PulseDesk.Domain.Comments;
using PulseDesk.Domain.Entities;
using PulseDesk.Infrastructure.Persistence;
using SQLitePCL;

namespace PulseDesk.Infrastructure.Repositories;

public class CommentRepository : ICommentRepository
{
    private readonly PulseDeskDbContext _context;

    public CommentRepository(PulseDeskDbContext context)
    {
        _context = context;
    }

    // public async Task<List<CommentRecord>> GetAllAsync()
    // {
    //     return await _context.Comments
    //         .OrderByDescending(c => c.CreatedAt)
    //         .ToListAsync();
    // }

    // public async Task<Comment?> GetByIdAsync(Guid id)
    // {
    //     return await _context.Comments.FirstOrDefaultAsync(c => c.Id == id);
    // }

    // public async Task<List<Comment>> GetByIdsAsync(List<int> ids)
    // {
    //     return await _context.Comments
    //         .Where(c => ids.Contains(c.Id))
    //         .ToListAsync();
    // }

    public async Task AddAsync(CommentDto comment)
    {
        var entity = new CommentRecord
        {
            Id = new CommentRecordId(Guid.Empty), // will be generated by the database
            IncidentId = new IncidentRecordId(comment.IncidentId),
            AuthorId = new UserRecordId(comment.AuthorId),
            Message = comment.Message,
            CreatedAt = comment.CreatedAt
        };
        await _context.Comments.AddAsync(entity);
        await SaveChangesAsync();
    }
    public Task SaveChangesAsync()
        => _context.SaveChangesAsync();

    public async Task<IEnumerable<CommentDto>> GetAllAsync()
    {
     return await _context.Comments
            .OrderByDescending(c => c.CreatedAt)
            .Select(c => new CommentDto(c.Id, c.IncidentId, c.AuthorId, c.Message, c.CreatedAt))
            .ToListAsync();   
    }

    public async Task<CommentDto?> GetByIdAsync(Guid id)
    {
        var comment = await _context.Comments.FirstOrDefaultAsync(c => c.Id == id);
        return comment != null ? new CommentDto(comment.Id, comment.IncidentId, comment.AuthorId, comment.Message, comment.CreatedAt) : null;
    }

}
