using PulseDesk.Application.Commands;
using PulseDesk.Application.DTOs;
using PulseDesk.Application.Repositories.Abstract;
using PulseDesk.Application.Services.Abstract;

namespace PulseDesk.Application.Services;

public class CommentService : ICommentService
{
    private readonly ICommentRepository _repository;

    public CommentService(ICommentRepository repository)
    {
        _repository = repository;
    }

    public async Task<CommentDto> CreateAsync(CreateCommentCommand command)
    {
        var comment = new CommentDto(
            Guid.Empty, // Id will be generated by the database
            command.IncidentId,
            command.AuthorId,
            command.Message,
            DateTime.UtcNow
        );
        await _repository.AddAsync(comment);
        return comment;
    }

    public async Task<IReadOnlyCollection<CommentDto>> GetAllAsync()
    {
        var comments = await _repository.GetAllAsync();
        return comments.Select(c => new CommentDto(
            c.Id,
            c.IncidentId,
            c.AuthorId,
            c.Message,
            c.CreatedAt
        )).ToList();
    }

    public async Task<CommentDto?> GetByIdAsync(Guid id)
    {
        return await _repository.GetByIdAsync(id);
    }

    // private static CommentDto Map(Comment comment) =>
    //     new(
    //         comment.Id,
    //         comment.Author.ToString(),
    //         comment.Message,
    //         comment.CreatedAt
    //     );
}
